[build-system]
requires = ["setuptools", "wheel", "setuptools_scm", "cmake", "scikit-build"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel.linux]
before-all = "yum install -y libasound2 libsndfile1 libsoundio-devel fftw3-devel"

[tool.cibuildwheel.macos]
before-all = "brew install libsndfile libsoundio"
